//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_Web_Forms_Application
{


	public partial class _Default
	{

		/// <summary>
		/// ViewStateCounter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::ASP.NET_Web_Forms_Application.StateCounter ViewStateCounter;

		/// <summary>
		/// SessionStateCounter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::ASP.NET_Web_Forms_Application.StateCounter SessionStateCounter;

		/// <summary>
		/// ApplicationCounter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::ASP.NET_Web_Forms_Application.StateCounter ApplicationCounter;

		/// <summary>
		/// CookieCounter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::ASP.NET_Web_Forms_Application.StateCounter CookieCounter;
	}
}
